#include "Ast.h"
#include "SymbolTable.h"
#include "Unit.h"
#include "Instruction.h"
#include "IRBuilder.h"
#include <string>
#include "Type.h"

extern FILE *yyout;
int Node::num = 0;
IRBuilder *Node::builder = nullptr;

Node::Node()
{
    seq = num++;
}

void Node::backPatch(std::vector<Instruction *> &list, BasicBlock *bb)
{
    for (auto &inst : list)
    {
        if (inst->isCond())
        {
            bb->addPred(dynamic_cast<CondBrInstruction *>(inst)->getParent());
            dynamic_cast<CondBrInstruction *>(inst)->getParent()->addSucc(bb);
            dynamic_cast<CondBrInstruction *>(inst)->setTrueBranch(bb);
        }
        else if (inst->isUncond())
        {
            bb->addPred(dynamic_cast<CondBrInstruction *>(inst)->getParent());
            dynamic_cast<CondBrInstruction *>(inst)->getParent()->addSucc(bb);
            dynamic_cast<UncondBrInstruction *>(inst)->setBranch(bb);
        }
    }
}

void Node::backPatchFalse(std::vector<Instruction *> &list, BasicBlock *bb)
{
    for (auto &inst : list)
    {
        if (inst->isCond())
        {
            bb->addPred(dynamic_cast<CondBrInstruction *>(inst)->getParent());
            dynamic_cast<CondBrInstruction *>(inst)->getParent()->addSucc(bb);
            dynamic_cast<CondBrInstruction *>(inst)->setFalseBranch(bb);
        }
        else if (inst->isUncond())
        {
            bb->addPred(dynamic_cast<CondBrInstruction *>(inst)->getParent());
            dynamic_cast<CondBrInstruction *>(inst)->getParent()->addSucc(bb);
            dynamic_cast<UncondBrInstruction *>(inst)->setBranch(bb);
        }
    }
}

std::vector<Instruction *> Node::merge(std::vector<Instruction *> &list1, std::vector<Instruction *> &list2)
{
    std::vector<Instruction *> res(list1);
    res.insert(res.end(), list2.begin(), list2.end());
    return res;
}

void Ast::genCode(Unit *unit)
{
    IRBuilder *builder = new IRBuilder(unit);
    Node::setIRBuilder(builder);
    fprintf(yyout, "declare i32 @getint()\ndeclare void @putint(i32)\ndeclare i32 @getch()\ndeclare void @putch(i32)\n");
    root->genCode();
}

void BinaryExpr::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    Function *func = bb->getParent();
    if (op == AND)
    {
        BasicBlock *trueBB = new BasicBlock(func); // 第二个子表达式生成的指令需要插入的位置
        expr1->genCode();
        backPatch(expr1->trueList(), trueBB);
        builder->setInsertBB(trueBB); // set the insert point to the trueBB so that intructions generated by expr2 will be inserted into it.
        expr2->genCode();
        true_list = expr2->trueList();
        false_list = merge(expr1->falseList(), expr2->falseList());
    }
    else if (op == OR)
    {
        BasicBlock *falseBB = new BasicBlock(func);
        expr1->genCode();
        backPatchFalse(expr1->falseList(), falseBB);
        builder->setInsertBB(falseBB);
        expr2->genCode();
        false_list = expr2->falseList();
        true_list = merge(expr1->trueList(), expr2->trueList());
    }
    else if (isRel())
    {
        expr1->genCode();
        expr2->genCode();
        Operand *src1 = expr1->getOperand();
        Operand *src2 = expr2->getOperand();
        int opcode;
        switch (op)
        {
        case GREAT:
            opcode = CmpInstruction::G;
            break;
        case GREATEQ:
            opcode = CmpInstruction::GE;
            break;
        case LESS:
            opcode = CmpInstruction::L;
            break;
        case LESSEQ:
            opcode = CmpInstruction::LE;
            break;
        case EQ:
            opcode = CmpInstruction::E;
            break;
        case NEQ:
            opcode = CmpInstruction::NE;
            break;
        default:
            break;
        }
        new CmpInstruction(opcode, dst, src1, src2, bb);
        true_list = merge(expr1->trueList(), expr2->trueList());
        false_list = merge(expr1->falseList(), expr2->falseList());
        Instruction *temp = new CondBrInstruction(nullptr, nullptr, dst, bb);
        this->trueList().push_back(temp);
        this->falseList().push_back(temp);
    }
    else if (isCal())
    {
        expr1->genCode();
        expr2->genCode();
        Operand *src1 = expr1->getOperand();
        Operand *src2 = expr2->getOperand();
        int opcode;
        switch (op)
        {
        case ADD:
            opcode = BinaryInstruction::ADD;
            break;
        case SUB:
            opcode = BinaryInstruction::SUB;
            break;
        case MUL:
            opcode = BinaryInstruction::MUL;
            break;
        case DIV:
            opcode = BinaryInstruction::DIV;
            break;
        case MOD:
            opcode = BinaryInstruction::MOD;
            break;
        }
        new BinaryInstruction(opcode, dst, src1, src2, bb);
    }
}

void Constant::genCode()
{
}

void Id::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry *>(symbolEntry)->getAddr();
    new LoadInstruction(dst, addr, bb);
}

void IfStmt::genCode()
{
    Function *func;
    BasicBlock *then_bb, *end_bb;

    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);

    then_bb->addPred(builder->getInsertBB());
    builder->getInsertBB()->addSucc(then_bb);
    end_bb->addPred(then_bb);
    then_bb->addSucc(end_bb);
    end_bb->addPred(builder->getInsertBB());
    builder->getInsertBB()->addSucc(end_bb);

    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatchFalse(cond->falseList(), end_bb);

    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    then_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_bb);

    builder->setInsertBB(end_bb);
}

void IfElseStmt::genCode()
{
    Function *func;
    BasicBlock *then_bb, *else_bb, *end_bb;
    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);
    else_bb = new BasicBlock(func);

    then_bb->addPred(builder->getInsertBB());
    builder->getInsertBB()->addSucc(then_bb);
    else_bb->addPred(builder->getInsertBB());
    builder->getInsertBB()->addSucc(else_bb);
    end_bb->addPred(then_bb);
    then_bb->addSucc(end_bb);
    end_bb->addPred(else_bb);
    else_bb->addSucc(end_bb);

    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatchFalse(cond->falseList(), else_bb);

    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    then_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_bb);

    builder->setInsertBB(else_bb);
    elseStmt->genCode();
    else_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, else_bb);

    builder->setInsertBB(end_bb);
}

void CompoundStmt::genCode()
{
    stmt->genCode();
}

void SeqNode::genCode()
{
    stmt1->genCode();
    stmt2->genCode();
}

void DeclStmt::genCode()
{
    for (auto iter = ids->ids.rbegin(); iter != ids->ids.rend(); iter++)
    {
        IdentifierSymbolEntry *se = dynamic_cast<IdentifierSymbolEntry *>((*iter)->getSymPtr());
        if (se->isGlobal())
        {
            SymbolEntry *addr_se = new IdentifierSymbolEntry(*se);
            Operand *addr = new Operand(addr_se);
            addr_se->setType(new PointerType(se->getType()));
            se->setAddr(addr);
            bool temp = false;
            Operand *src;
            for (int i = 0; i < (int)ids->value.size(); i++)
            {
                if (ids->value[i]->lval->symbolEntry == se)
                {
                    ids->value[i]->genCode();
                    src = ids->value[i]->expr->getOperand();
                    temp = true;
                    break;
                }
            }
            if (temp == false)
            {
                SymbolEntry *se = new ConstantSymbolEntry(TypeSystem::intType, 0);
                Constant *digit = new Constant(se);
                src = digit->getOperand();
            }
            Instruction *alloca = new AllocaInitInstruction(src, addr, se);
            alloca->output();
        }
        else if (se->isLocal())
        {
            Function *func = builder->getInsertBB()->getParent();
            BasicBlock *entry = func->getEntry();
            Instruction *alloca;
            Operand *addr;
            SymbolEntry *addr_se;
            Type *type;
            type = new PointerType(se->getType());
            addr_se = new TemporarySymbolEntry(type, SymbolTable::getLabel());
            addr = new Operand(addr_se);
            alloca = new AllocaInstruction(addr, se); // allocate space for local id in function stack.
            entry->insertFront(alloca);               // allocate instructions should be inserted into the begin of the entry block.
            se->setAddr(addr);                        // set the addr operand in symbol entry so that we can use it in subsequent code generation.
        }
    }
    for (int i = 0; i < (int)ids->value.size(); i++)
    {
        IdentifierSymbolEntry *se = dynamic_cast<IdentifierSymbolEntry *>(ids->value[i]->lval->getSymPtr());
        if (se->isGlobal())
        {
            continue;
        }
        else if (se->isLocal())
        {
            Operand *addr = dynamic_cast<IdentifierSymbolEntry *>(ids->value[i]->lval->getSymPtr())->getAddr();
            se->setAddr(addr);
            ids->value[i]->genCode();
        }
    }
}

void ReturnStmt::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    retValue->genCode();
    Operand *src = retValue->getOperand();
    new RetInstruction(src, bb);
}

void AssignStmt::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    expr->genCode();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry *>(lval->getSymPtr())->getAddr();
    Operand *src = expr->getOperand();
    new StoreInstruction(addr, src, bb);
}

void OneStmt::genCode()
{
    expr->genCode();
}

void Empty::genCode()
{
}

void FuncRParams::genCode()
{
}

void FuncFParam::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry *>(symbolEntry)->getAddr();
    new LoadInstruction(dst, addr, bb);
}

void FuncFParams::genCode()
{
    Function *func = builder->getInsertBB()->getParent();
    for (int i = 0; i < (int)params.size(); i++)
    {
        IdentifierSymbolEntry *se = dynamic_cast<IdentifierSymbolEntry *>(params[i]->getSymPtr());
        Type *type1 = new PointerType(se->getType());
        Type *type2 = new IntType(32);
        SymbolEntry *addr_se = new TemporarySymbolEntry(type2, SymbolTable::getLabel());
        Operand *addr = new Operand(addr_se);
        SymbolTable ::num++; // 为了分配新的
        SymbolEntry *addr_se2 = new TemporarySymbolEntry(type1, SymbolTable::getLabel());
        Operand *addr2 = new Operand(addr_se2);
        BasicBlock *entry = func->getEntry();
        Instruction *alloca;
        alloca = new AllocaInstruction(addr2, se); // allocate space for local id in function stack.
        entry->insertBack(alloca);                 // allocate instructions should be inserted into the begin of the entry block.
        StoreInstruction *store = new StoreInstruction(addr2, addr);
        entry->insertBack(store);
        se->setAddr(addr2);
        func->insertParam(addr);
    }
}

void FunctionDef::genCode()
{
    Unit *unit = builder->getUnit();
    Function *func = new Function(unit, se);
    BasicBlock *entry = func->getEntry();
    builder->setInsertBB(entry);
    if (params != nullptr)
        params->genCode();
    stmt->genCode();
}

void FunctionCall::genCode()
{
    std::vector<Operand *> temp_params;
    if (params != nullptr)
        for (unsigned i = 0; i < params->expr.size(); i++)
        {
            if (params->expr[i] != nullptr)
                params->expr[i]->genCode();
            temp_params.push_back(params->expr[i]->getOperand());
        }
    BasicBlock *entry = builder->getInsertBB();
    Type *type2 = new IntType(32);
    SymbolTable ::num++; // 为了分配新的
    SymbolEntry *addr_se2 = new TemporarySymbolEntry(type2, SymbolTable::getLabel());
    dst = new Operand(addr_se2);
    FunctionCallInstruction *temp = new FunctionCallInstruction(dst, symbolEntry, temp_params);
    entry->insertBack(temp);
}

void ConstIdList::genCode()
{
}

void IdList::genCode()
{
}

void WhileStmt::genCode()
{
    Function *func;
    BasicBlock *loop_bb, *end_bb, *cond_bb;

    func = builder->getInsertBB()->getParent();
    loop_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);
    cond_bb = new BasicBlock(func);

    UncondBrInstruction *temp = new UncondBrInstruction(cond_bb, builder->getInsertBB());
    temp->output();
    // 设置前后
    cond_bb->addPred(builder->getInsertBB());
    builder->getInsertBB()->addSucc(cond_bb);
    loop_bb->addPred(cond_bb);
    cond_bb->addSucc(loop_bb);
    end_bb->addPred(loop_bb);
    loop_bb->addSucc(end_bb);
    end_bb->addPred(cond_bb);
    cond_bb->addSucc(end_bb);
    builder->setInsertBB(cond_bb);
    cond->genCode();
    backPatch(cond->trueList(), loop_bb);
    backPatchFalse(cond->falseList(), end_bb);
    builder->setInsertBB(loop_bb);
    loop->genCode();
    loop_bb = builder->getInsertBB();
    new CondBrInstruction(cond_bb, end_bb, cond->getOperand(), loop_bb);

    builder->setInsertBB(end_bb);
}

void ConstDeclStmt::genCode()
{
    for (int i = 0; i < (int)const_ids->const_ids.size(); i++)
    {
        IdentifierSymbolEntry *se = dynamic_cast<IdentifierSymbolEntry *>(const_ids->const_ids[i]->getSymPtr());
        if (se->isGlobal())
        {
            Operand *addr;
            SymbolEntry *addr_se;
            addr_se = new IdentifierSymbolEntry(*se);
            addr_se->setType(new PointerType(se->getType()));
            addr = new Operand(addr_se);
            se->setAddr(addr);
            const_ids->value[i]->genCode();
            Operand *src = const_ids->value[i]->expr->getOperand();
            Instruction *alloca = new AllocaInitInstruction(src, addr, se);
            alloca->output();
        }
        else if (se->isLocal())
        {
            Function *func = builder->getInsertBB()->getParent();
            BasicBlock *entry = func->getEntry();
            Instruction *alloca;
            Operand *addr;
            SymbolEntry *addr_se;
            Type *type;
            type = new PointerType(se->getType());
            addr_se = new TemporarySymbolEntry(type, SymbolTable::getLabel());
            addr = new Operand(addr_se);
            alloca = new AllocaInstruction(addr, se); // allocate space for local id in function stack.
            entry->insertFront(alloca);               // allocate instructions should be inserted into the begin of the entry block.
            se->setAddr(addr);

            const_ids->value[i]->expr->genCode();
            Operand *addr1 = dynamic_cast<IdentifierSymbolEntry *>(const_ids->value[i]->lval->getSymPtr())->getAddr();
            se->setAddr(addr1);
            Operand *src = const_ids->value[i]->expr->getOperand();
            BasicBlock *ttt = builder->getInsertBB();
            new StoreInstruction(addr1, src, ttt); // set the addr operand in symbol entry so that we can use it in subsequent code generation.
        }
    }
}

void ContinueStmt::genCode()
{
}

void BreakStmt::genCode()
{
}

void ConstId::genCode()
{
}

void OneExpr::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    expr->genCode();
    Operand *src = expr->getOperand();
    if (src->getType()->isBool())
    {
        Operand *t = new Operand(new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel()));
        new ZextInstruction(t, expr->dst, bb);
        expr->dst = t;
        src = t;
    }
    int opcode;
    switch (op)
    {
    case ADD:
        opcode = BinaryInstruction::ADD;
        break;
    case SUB:
        opcode = BinaryInstruction::SUB;
        break;
    default:
        break;
    }
    SymbolEntry *se = new ConstantSymbolEntry(TypeSystem::intType, 0);
    Constant *digit = new Constant(se);
    new BinaryInstruction(opcode, dst, digit->getOperand(), src, bb);
    isCond = expr->isCond;
}

void Ast::typeCheck()
{
    fprintf(yyout, ";TypeCheck Begin!\n");
    if (root != nullptr)
        root->typeCheck();
}

void FunctionDef::typeCheck()
{
    fprintf(yyout, ";FunctionDef %s typecheck Begin!\n", se->toStr().c_str());
    stmt->typeCheck();
}

void BinaryExpr::typeCheck()
{
    Type *type1 = expr1->getSymPtr()->getType();
    Type *type2 = expr2->getSymPtr()->getType();
    if (type1 != type2)
    {
        fprintf(stderr, "type %s and %s mismatch",
                type1->toStr().c_str(), type2->toStr().c_str());
        exit(EXIT_FAILURE);
    }
    fprintf(yyout, ";BinaryExpr TypeCheck OK!\n");
    symbolEntry->setType(type1);
    expr1->typeCheck();
    expr2->typeCheck();
}

void Constant::typeCheck()
{
}

void Id::typeCheck()
{
}

void IfStmt::typeCheck()
{
    cond->typeCheck();
    thenStmt->typeCheck();
}

void IfElseStmt::typeCheck()
{
}

void CompoundStmt::typeCheck()
{
}

void SeqNode::typeCheck()
{
}

void DeclStmt::typeCheck()
{
}

void ReturnStmt::typeCheck()
{
    fprintf(yyout, ";Return Statement Type Check begin!\n");
    if (retValue != nullptr)
    {
        retValue->typeCheck();
        type = retValue->getOperand()->getType();
    }
    else
    {
        type = new VoidType();
    }
}

void AssignStmt::typeCheck()
{
}

void OneStmt::typeCheck()
{
}

void FuncRParams::typeCheck()
{
}

void Empty::typeCheck()
{
}

void FuncFParam::typeCheck()
{
}

void FuncFParams::typeCheck()
{
}

void ConstIdList::typeCheck()
{
}

void IdList::typeCheck()
{
}

void WhileStmt::typeCheck()
{
}

void FunctionCall::typeCheck()
{
}

void ConstDeclStmt::typeCheck()
{
}

void ContinueStmt::typeCheck()
{
}

void BreakStmt::typeCheck()
{
}

void ConstId::typeCheck()
{
}

void OneExpr::typeCheck()
{
    Type *type = expr->getSymPtr()->getType();
    if (type->isVoid())
    {
        fprintf(stderr, "type can't be void");
        exit(EXIT_FAILURE);
    }
    symbolEntry->setType(type);
    expr->typeCheck();
}

void Ast::output()
{
    fprintf(yyout, "program\n");
    if (root != nullptr)
        root->output(4);
}

void BinaryExpr::output(int level)
{
    std::string op_str;
    switch (op)
    {
    case ADD:
        op_str = "add";
        break;
    case SUB:
        op_str = "sub";
        break;
    case AND:
        op_str = "and";
        break;
    case OR:
        op_str = "or";
        break;
    case LESS:
        op_str = "less";
        break;
    case GREAT:
        op_str = "great";
        break;
    case LESSEQ:
        op_str = "lesseq";
        break;
    case GREATEQ:
        op_str = "greateq";
        break;
    case EQ:
        op_str = "eq";
        break;
    case NEQ:
        op_str = "neq";
        break;
    case DIV:
        op_str = "div";
        break;
    case MUL:
        op_str = "mul";
        break;
    case MOD:
        op_str = "mod";
        break;
    }
    fprintf(yyout, "%*cBinaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr1->output(level + 4);
    expr2->output(level + 4);
}

void OneExpr::output(int level)
{
    std::string op_str;
    switch (op)
    {
    case SUB:
        op_str = "negative";
        break;
    case ADD:
        op_str = "positive";
        break;
    case EXCLAMATION:
        op_str = "anti";
        break;
    }
    fprintf(yyout, "%*cOneExpr\top: %s\n", level, ' ', op_str.c_str());
    expr->output(level + 4);
}

void Constant::output(int level)
{
    std::string type, value;
    type = symbolEntry->getType()->toStr();
    value = symbolEntry->toStr();
    fprintf(yyout, "%*cIntegerLiteral\tvalue: %s\ttype: %s\n", level, ' ',
            value.c_str(), type.c_str());
}

void ConstId::output(int level)
{
    std::string name, type;
    int scope;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    scope = dynamic_cast<IdentifierSymbolEntry *>(symbolEntry)->getScope();
    fprintf(yyout, "%*cConstId\tname: %s\tscope: %d\ttype: %s\n", level, ' ',
            name.c_str(), scope, type.c_str());
}

void Id::output(int level)
{
    std::string name, type;
    int scope;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    scope = dynamic_cast<IdentifierSymbolEntry *>(symbolEntry)->getScope();
    fprintf(yyout, "%*cId\tname: %s\tscope: %d\ttype: %s\n", level, ' ',
            name.c_str(), scope, type.c_str());
}

void FuncFParam::output(int level)
{
    std::string name, type;
    int scope;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    scope = dynamic_cast<IdentifierSymbolEntry *>(symbolEntry)->getScope();
    fprintf(yyout, "%*cFuncFParam\tname:%s\tscope:%d\ttype:%s\n", level, ' ',
            name.c_str(), scope, type.c_str());
}

void CompoundStmt::output(int level)
{
    fprintf(yyout, "%*cCompoundStmt\n", level, ' ');
    stmt->output(level + 4);
}

void SeqNode::output(int level)
{
    fprintf(yyout, "%*cSequence\n", level, ' ');
    stmt1->output(level + 4);
    stmt2->output(level + 4);
}

void BreakStmt::output(int level)
{
    fprintf(yyout, "%*cBreakStmt\n", level, ' ');
}

void ContinueStmt::output(int level)
{
    fprintf(yyout, "%*cContinueStmt\n", level, ' ');
}

void DeclStmt::output(int level)
{
    fprintf(yyout, "%*cDeclStmt\n", level, ' ');
    ids->output(level + 4);
}

void ConstDeclStmt::output(int level)
{
    fprintf(yyout, "%*cConstDeclStmt\n", level, ' ');
    const_ids->output(level + 4);
}

void IfStmt::output(int level)
{
    fprintf(yyout, "%*cIfStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
}

void IfElseStmt::output(int level)
{
    fprintf(yyout, "%*cIfElseStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
    elseStmt->output(level + 4);
}

void ReturnStmt::output(int level)
{
    fprintf(yyout, "%*cReturnStmt\n", level, ' ');
    retValue->output(level + 4);
}

void AssignStmt::output(int level)
{
    fprintf(yyout, "%*cAssignStmt\n", level, ' ');
    lval->output(level + 4);
    expr->output(level + 4);
}

void FunctionDef::output(int level)
{
    std::string name, type;
    name = se->toStr();
    type = se->getType()->toStr();
    fprintf(yyout, "%*cFunctionDefine function name: %s, type: %s\n", level, ' ',
            name.c_str(), type.c_str());
    if (params != nullptr)
    {
        params->output(level + 4);
    }
    stmt->output(level + 4);
}

void FunctionCall::output(int level)
{
    std::string name, type;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    fprintf(yyout, "%*cFuncCall\tname: %s\ttype: %s\n", level, ' ',
            name.c_str(), type.c_str());
    if (params != nullptr)
    {
        params->output(level + 4);
    }
}

void WhileStmt::output(int level)
{
    fprintf(yyout, "%*cWhileStmt\n", level, ' ');
    cond->output(level + 4);
    loop->output(level + 4);
}

void IdList::output(int level)
{
    fprintf(yyout, "%*cIdList\n", level, ' ');
    for (int i = 0; i < (int)ids.size(); i++)
        ids[i]->output(level + 4);
    for (int i = 0; i < (int)value.size(); i++)
        value[i]->output(level + 4);
}
void ConstIdList::output(int level)
{
    fprintf(yyout, "%*cConstIdList\n", level, ' ');
    for (int i = 0; i < (int)const_ids.size(); i++)
    {
        const_ids[i]->output(level + 4);
        value[i]->output(level + 4);
    }
}

void FuncFParams::output(int level)
{
    fprintf(yyout, "%*cFuncFParams\n", level, ' ');
    for (int i = 0; i < (int)params.size(); i++)
    {
        params[i]->output(level + 4);
    }
    for (int i = 0; i < (int)value.size(); i++)
    {
        value[i]->output(level + 4);
    }
}

void FuncRParams::output(int level)
{
    fprintf(yyout, "%*cFuncRParams\n", level, ' ');
    for (int i = 0; i < (int)expr.size(); i++)
    {
        expr[i]->output(level + 4);
    }
}

void Empty::output(int level)
{
    fprintf(yyout, "%*cEmpty Statement\n", level, ' ');
}

void OneStmt::output(int level)
{
    fprintf(yyout, "%*cOne Statement\n", level, ' ');
    expr->output(level + 4);
}